spring.application.name=RemontexWeb
# Налаштування підключення до бази даних PostgreSQL у Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/remontex
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Налаштування Hibernate & JPA
# 'update' автоматично створить таблиці в чистій базі або оновить їх, якщо ти додаси нові поля
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Логування SQL-запитів у консоль (дуже зручно для відладки)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# Вимикаємо набридливе попередження про Open-In-View в логах
spring.jpa.open-in-view=false

# Налаштування сервера
server.port=8080